# Generated by Django 5.2.8 on 2026-01-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
